name: Node CI

on:
  push:
    branches:
    - main
    
    
jobs:  

  build_and_test:   
  
    runs-on: ubuntu-latest 
   
    steps:

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'

    - name: Checkout to the repository
      uses: actions/checkout@v3

    - name: Npm install, build and test
      run: |
          ls -lart
          npm install
          ls -lart
          
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Artifacts
        path: |
             node_modules/
             package-lock.json

  download_artifact:   
  
    needs: build_and_test
    runs-on: ubuntu-latest 
   
    steps:

    - name: Checkout to the repository
      uses: actions/checkout@v3

    - name: Download Artifacts
      uses: actions/download-artifact@v2
      with:
        name: Artifacts
        
    - name: Show Workspace Files
      run: |
          ls -lart       

  deploy:   
  
    needs: [build_and_test, download_artifact]
    runs-on: ubuntu-latest 
   
    steps:

    - name: Checkout to the repository
      uses: actions/checkout@v3
 
    - name: Start Minikube Cluster
      uses: medyagh/setup-minikube@master

    - name: Testing the cluster!
      run: kubectl get pods -A

    - name: Authenticate GitHub Actions with Cluster
      run: kubectl create clusterrolebinding serviceaccounts-cluster-admin --clusterrole=cluster-admin --group=system:serviceaccounts

# Deploy the Docker image on the local minikube cluster

    - name: Deploy to Minikube
      run: |
          kubectl apply -f Deployment/mongodb.yaml
    
