name: Node CI

on:
  push:
    branches:
    - main
    
jobs:  

  build_and_test:   
    runs-on: ubuntu-latest
    
   
    steps:

    - run: |
          ls -lart
          mkdir -p workspace
          echo "GITHUB_WORKSPACE: ${GITHUB_WORKSPACE}"
          cd ${GITHUB_WORKSPACE}/
          ls -lart
    
    - name: Checkout to the repository
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'

    - name: Npm install, build and test
      run: npm install
      
    - name: Workspace
      run: |
          ls -lart
          echo "GITHUB_WORKSPACE: ${GITHUB_WORKSPACE}"
          cd ${GITHUB_WORKSPACE}/
          ls -lart
          
