name: Node CI

on:
  push:
    branches:
    - main
    
jobs:  

  build_and_test:   
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]
   
    steps:

    - name: Checkout to the repository
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Npm install, build and test
      run: npm install
