name: Node CI

on:
  push:
    branches:
    - main
    
    
jobs:  

  build_and_test:   
    runs-on: ubuntu-latest 
   
    steps:

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'

    - name: Checkout to the repository
      uses: actions/checkout@v3

    - name: Npm install, build and test
      run: |
          npm install
          
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Artifacts
        path: |
             node_modules/
             package-lock.json
