name: Node CI

on:
  push:
    branches:
    - main
    
jobs:  

  build_and_test:   
    runs-on: ubuntu-latest
    
   
    steps:

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'

    - name: Checkout to the repository
      uses: actions/checkout@v3

    - run: mkdir -p workspace

    - name: Npm install, build and test
      run: |
          cd workspace/
          npm install
          
